spring.application.name=events
spring.datasource.url=jdbc:postgresql://localhost:5432/events
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.google.client-id=95312326754-mbsqgtkd7u85inebdesai89t1bk4lfh7.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo

server.port=8080

jwt.secret=cetdq@@@@&&tecleestultras###"gjvhccgxfdxfdwfgecrete12345678901234567890
jwt.duration=900000
jwt.refresh-token.duration=604800000
jwt.refresh-token.secret=cetdq@@@@&&tecleestultgdcdgdgdxx14121278hzbddf;b

app.base-url=http://localhost:8080
app.api-version=/api/v1
app.frontend-base-url=http://localhost:3000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=infomng2022@gmail.com
spring.mail.password=fiplvcktgxpadfgm
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

supabase.project-url=https://mdpvwnzgkazrytkdesle.supabase.co
supabase.api-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcHZ3bnpna2F6cnl0a2Rlc2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMzY0NTIsImV4cCI6MjA1NTgxMjQ1Mn0.yVQZhW1VV3PhefxrtnUrDUaJPiFsBuuBePksuLRv41Q
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kcHZ3bnpna2F6cnl0a2Rlc2xlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDIzNjQ1MiwiZXhwIjoyMDU1ODEyNDUyfQ.fdMT0pSZCLX2RNCJ1LsUZd7kwn1mrhlEJZOaCCm11wg
supabase.bucket-name=stockbucket